opgaven/week3/opdracht2/src/app/households/models.py
from app import db
from sqlalchemy.ext.associationproxy import association_proxy
from sqlalchemy.ext.hybrid import hybrid_property

# device_household = db.Table('apparaat_huishouden',
#     db.Column('id', db.Integer, primary_key=True),
#     db.Column('huishouden_fk', db.Integer, db.ForeignKey('huishouden.id')),
#     db.Column('apparaat_fk', db.Integer, db.ForeignKey('apparaat.id'))
# )

household_user = db.Table('huishouden_gebruiker',
    db.Column('id', db.Integer, primary_key=True),
    db.Column('huishouden_fk', db.Integer, db.ForeignKey('huishouden.id')),
    db.Column('gebruiker_fk', db.Integer, db.ForeignKey('gebruiker.id'))
)

class Household(db.Model):
    __tablename__ = 'huishouden'

    id = db.Column('id', db.Integer, primary_key=True)
    postcode = db.Column('postcode', db.String(6))
    housenumber = db.Column('huisnummer', db.String(10))
    size = db.Column('grootte', db.Integer)
    users = db.relationship('User', secondary=household_user, backref='households')

    devices = association_proxy('householdDevices', 'device')

    def __init__(self, postcode=None, housenumber=None, size=None):
        self.postcode = postcode
        self.housenumber = housenumber
        self.size = size

    def __repr__(self):
        return '<Household %r %r>' % (self.postcode, self.housenumber)

class Device(db.Model):
    __tablename__ = 'apparaat'

    id = db.Column('id', db.Integer, primary_key=True)
    name = db.Column('naam', db.String(64))
    category = db.Column('categorie', db.String(64))
    max = db.Column('max', db.Integer)

    households = association_proxy('householdDevices', 'household')

    def __init__(self, name=None, category=None, max=None, households=None):
        self.name = name
        self.category = category
        self.max = max
        self.households = households

    def __repr__(self):
        return '<Device %r>' % (self.name)

class HouseholdDevice(db.Model):
    __tablename__ = 'apparaat_huishouden'

    id = db.Column('id', db.Integer, primary_key=True)
    household_id = db.Column('huishouden_fk', db.Integer, db.ForeignKey('huishouden.id'))
    device_id = db.Column('apparaat_fk', db.Integer, db.ForeignKey('apparaat.id'))

    household = db.relationship(Household, backref='householdDevices')
    device = db.relationship(Device, backref='householdDevices')

    def __init__(self, household=None, device=None):
        self.household_id = household.id
        self.device_id = device.id

    @hybrid_property
    def name(self):
        return self.device.name

    @hybrid_property
    def category(self):
        return self.device.category

    @hybrid_property
    def max(self):
        return self.device.max

    def __repr__(self):
        return '<HouseholdDevice %r %r %r>' % (self.id, self.household, self.device)

opgaven/week3/opdracht2/src/app/households/forms.py
from app.households.models import Device
from flask.ext.wtf import Form
from wtforms import RadioField
from wtforms.validators import Required

def deviceChoices():
    devices = Device.query.order_by(Device.name).all()
    choices = []

    for device in devices:
        choices.append((str(device.id), device.name))

    return choices

class DeviceForm(Form):
    device = RadioField('Type', [Required()], choices=deviceChoices())

opgaven/week3/opdracht2/src/app/households/views.py
from flask import Flask, Blueprint, g, flash, session, redirect, request, render_template
from flask.ext.login import login_required, current_user
from app import app, db
from app.households.models import Device, HouseholdDevice
from app.households.forms import DeviceForm

mod = Blueprint('households', __name__, url_prefix='/households')

@mod.route('/')
@login_required
def index():
    return render_template('households/index.html', households=current_user.households)

@mod.route('/add-device', methods=['GET', 'POST'])
@login_required
def add_device():
    form = DeviceForm(request.form)

    if form.validate_on_submit():
        device = Device.query.get(form.device.data)

        householdDevice = HouseholdDevice(
            household=current_user.households[0],
            device=device
        )

        db.session.add(householdDevice)
        db.session.commit()

        return redirect('/')

    return render_template('households/add-device.html', form=form)

opgaven/week3/opdracht2/src/app/templates/aanmelden.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>NRG Web</title>
    
    
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    
    <link href="http://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css" rel="stylesheet">
    <link href="../static/signup.css" rel="stylesheet">
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" ><a href="/">Home</a></li>
            <li role="presentation"><a href="/showLogin">Inloggen</a></li>
            <li role="presentation" class="active"><a href="#">Aanmelden</a></li>
          </ul>
        </nav>
        <h3 class="text-muted">NRG Web</h3>
      </div>
      
      <div class="jumbotron">
        <h1>NRG Web</h1>
        <form class="form-signin" action="/signUp" method="POST">
          <label for="inputName" class="sr-only">Name</label>
          <input type="name" name="inputName" id="inputName" class="form-control" placeholder="Naam" required autofocus>
          <label for="inputEmail" class="sr-only">Email adres</label>
          <input type="email" name="inputEmail" id="inputEmail" class="form-control" placeholder="Email addres" required autofocus>
          <label for="inputPassword" class="sr-only">Password</label>
          <input type="password" name="inputPassword" id="inputPassword" class="form-control" placeholder="Wachtwoord" required>
          <label for="inputPhonenumber" class="sr-only">Telefoonnummer</label>
          <input type="number" name="inputPhonenumber" id="inputPhonenumber" class="form-control" placeholder="Telefoonnummer" required>
          <p></p>
          <input type="submit" id="btnSignUp" class="btn btn-lg btn-primary btn-block-small" value="Aanmelden">
        </form>
      </div>
      <footer class="footer">
        <p>&copy; NRG 2015</p>
      </footer>
    </div>
    <script type="text/javascript">
    // $(function() {
    // $('#btnSignUp').click(function() {
    
    // $.ajax({
    // url: '/signUp',
    // data: $('form').serialize(),
    // type: 'POST',
    // success: function(response) {
    // console.log(response);
    // },
    // error: function(error) {
    // console.log(error);
    // }
    // });
    // });
    // });
    </script>
  </body>
</html>
<!-- <input type="number" name="inputHousehold" id="inputHousehold" class="form-control" placeholder="Grootte van huishouden (minstens 1)" required> -->
<!-- <label for="inputHousehold" class="sr-only">Grootte huishouden</label> -->

opgaven/week3/opdracht2/src/app/templates/addDevice.html
<!DOCTYPE html>
<html lang="en">
    
    <head>
        <title>NRG Web</title>
        
        
        <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
        
        <link href="http://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css" rel="stylesheet">
        
        <script src="../static/js/jquery-1.11.2.js"></script>
        
        
    </head>
    
    <body>
        <div class="container">
            <div class="header">
                <nav>
                    <ul class="nav nav-pills pull-right">
                        <li role="presentation"><a href="/showHouseholds">Huishoudens</a></li>
                        <li role="presentation"><a href="/logout">Logout</a>
                    </li>
                </ul>
            </nav>
            <h3 class="text-muted">NRG Web</h3>
        </div>
        <section>
            <form class="form-horizontal" method="POST" action="/addDevice">
                <fieldset>
                    
                    <!-- Form Name -->
                    <legend>Apparaat toevoegen</legend>
                    
                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="txtName">Naam</label>
                        <div class="col-md-4">
                            <input id="txtTitle" name="inputName" type="text"  class="form-control input-md" required>
                        </div>
                    </div>
                    
                    <!-- input -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="txtBrand">Merk</label>
                        <div class="col-md-4">
                            <input class="form-control" id="txtBrand" name="inputBrand" required></input>
                        </div>
                    </div>
                    <!-- select -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="inputType">Type</label>
                        <div class="col-md-4">
                            <select  class="form-control" id="inputType" name="inputType">
                                <option value="0">Zonnepaneel</option>
                                <option value="1">Windmolen</option>
                                <option value="2">Overig</option>
                            </select>
                        </div>
                    </div>
                    <!-- Button -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="singlebutton"></label>
                        <div class="col-md-4">
                            <input id="singlebutton" name="singlebutton" class="btn btn-primary" type="submit" value="Toevoegen" />
                        </div>
                    </div>
                    
                </fieldset>
            </form>
            
        </section>
        <footer class="footer">
            <p>&copy; Company 2015</p>
        </footer>
        
    </div>
</body>
</html>

opgaven/week3/opdracht2/src/app/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>Hanze NRG</title>

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
		<link rel="stylesheet" href="/static/css/c3.min.css">

		<script src="/static/js/d3.min.js"></script>
		<script src="/static/js/c3.min.js"></script>
		<script src="/static/js/underscore.min.js"></script>
		<script src="/static/js/jquery.min.js"></script>
	</head>
	<body>
		<div class="container">
			<header class="header">
			{% if current_user.is_authenticated %}
				<nav>
					<ul class="nav nav-pills pull-right">
						<li role="presentation"><a href="/">Home</a></li>
						<li role="presentation"><a href="{{ url_for('households.index') }}">Mijn huishoudens</a></li>
						<li role="presentation"><a href="{{ url_for('logout') }}">uitloggen</a></li>
					</ul>
				</nav>
				{% endif %}
				<h1><a href="/">Hanze NRG</a></h1>
				<hr>
			</header>

			{% with messages = get_flashed_messages(with_categories=true) %}
				{% if messages %}
					{% for category, message in messages %}
						<div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
					{% endfor %}
				{% endif %}
			{% endwith %}

			{% block content %}{% endblock %}
		</div>
	</body>
</html>	

opgaven/week3/opdracht2/src/app/templates/error.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Unauthorized Access:: NGR Web</title>

   
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <link href="http://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css" rel="stylesheet">
    <link href="../static/css/signup.css" rel="stylesheet">
    
   
  </head>

  <body>

    <div class="container">
      <div class="header">
        <nav>
           <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active"><a href="#">Home</a></li>
            <li role="presentation"><a href="/showLogin">Sign In</a></li>
 	    <li role="presentation"><a href="/showSignUp">Sign Up</a></li>
          </ul>
        </nav>
        <h3 class="text-muted">NGR Web</h3>
      </div>

      <div class="jumbotron">
        <h1>{{error}}</h1>
        
      </div>

      

      <footer class="footer">
        <p>&copy; NGR Web 2015</p>
      </footer>

    </div>
  </body>
</html>

opgaven/week3/opdracht2/src/app/templates/households.html
<!DOCTYPE html>
<html lang="en">
    
    <head>
        <title>NRG Web</title>
        
        
        <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
        
        <link href="http://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css" rel="stylesheet">
        
        <script src="../static/js/jquery-1.11.2.js"></script>
        
        
    </head>
    
    <body>
        <div class="container">
            <div class="header">
                <nav>
                    <ul class="nav nav-pills pull-right">
                        
                        <li role="presentation"><a href="/logout">Logout</a>
                    </li>
                </ul>
                <h3 class="text-muted">NRG Web</h3>
            </div>
            <section>
                {% if household %}
                    <table class="table table-hover" >
                        <caption>Huishouden</caption>
                        <thead>
                            <tr>
                                
                                <th>Postcode</th>
                                <th>Huisnunmmer</th>
                                <th>Grootte</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                {% for n in household %}
                                    <td>{{ household[n] }}</td>
                                {% endfor %}
                            </tr>
                        </tbody>
                    </table>
                {% else %}
                    <em>Nog geen huishouden bij deze gebruiker.</em>
                    <p></p>
                    <p></p>
                    <button type="button" class="btn btn-primary" onclick="#">Huishouden toevoegen </button>
                </li>
            {% endif %}
            <table class="table table-hover">
                <caption>Apparaten</caption>
                <thead>
                    <tr>
                        <th>Naam apparaat</th>
                        <th>Merk</th>
                        <th>Max wattage</th>
                    </tr>
                </thead>
                <tbody>
                    <form  class="request.form" action="/removeDeviceById" method="POST" role="form">
                        {% if devices %}
                            {% for n in devices %}
                                <tr>
                                    
                                    <td>{{ n.naam }}</td>
                                    <td>{{ n.merk }}</td>
                                    <td>{{ n.max }}</td>
                                    <td>
                                        <input type="hidden" value={{ n.id }} name="inputDelete"></input>
                                        <button class="btn btn-danger"" type="submit">Verwijder</button>
                                    </td>
                                </tr>
                            {% endfor %}
                        </form>
                    </tbody>
                </table>
            {% else %}
                <em>Nog geen Apparaten toegevoegd.</em>
                <p></p>
                <p></p>
                <button type="button" class="btn btn-primary" onclick="#">Apparaat toevoegen </button>
            </li>
        {% endif %}
         <form  class="request.form" action="/showAddDevice"  role="form">
        <button type="submit" class="btn btn-primary" >Apparaat toevoegen </button>
        </form>
    </section>
    <footer class="footer">
        <p>&copy; Company 2015</p>
    </footer>
    
</div>
</body>
</html>

opgaven/week3/opdracht2/src/app/templates/index.html
{% import 'households/household.html' as household %}

{% extends 'base.html' %}
{% block content %}
    <h1>Hello {{user.name}}</h1>

    <div class="households">
    {% for _household in user.households %}
        {{ household.single(_household) }}
    {% endfor %}
    </div>
{% endblock %}

opgaven/week3/opdracht2/src/app/templates/inloggen.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>NRG Web</title>
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css" rel="stylesheet">
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>

</head>

<body>


<div class="container">
    <div class="header">
        <nav>
            <ul class="nav nav-pills pull-right">
                <li role="presentation"><a href="/">Home</a></li>
                <li role="presentation" class="active"><a href="/showLogin">Inloggen</a></li>
                <li role="presentation"><a href="/showSignUp">Aanmelden</a></li>
            </ul>
        </nav>
        <h3 class="text-muted">NRG Web</h3>
    </div>


    <div class="jumbotron">
        <h1>NRG Web</h1>

        <form class="form-signin" action="/validateLogin" method="post">
            <label for="inputEmail" class="sr-only">Email adres</label>
            <input type="email" name="inputEmail" id="inputEmail" class="form-control" placeholder="Email addres"
                   required autofocus>
            <label for="inputPassword" class="sr-only">Wachtwoord</label>
            <input type="password" name="inputPassword" id="inputPassword" class="form-control" placeholder="Wachtwoord"
                   required>

            <p></p>
            <button id="btnSignIn" class="btn btn-lg btn-primary btn-block-small" type="submit">Inloggen</button>
        </form>
    </div>


    <footer class="footer">
        <p>&copy; NRG 2015</p>
    </footer>

</div>
</body>
</html>

opgaven/week3/opdracht2/src/app/templates/userHome.html
<!DOCTYPE html>
<html lang="en">
    
    <head>
        <title>NRG Web</title>
        
        
        <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
        
        <link href="http://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css" rel="stylesheet">
        <link href="../static/css/signup.css" rel="stylesheet">
        
        
    </head>
    
    <body>
        
        <div class="container">
            <div class="header">
                <nav>
                    <ul class="nav nav-pills pull-right">
                        <li role="presentation" class="active" ><a href="/userHome">Home</a></li>
                        <li role="presentation"><a href="/showHouseholds">Huishoudens</a></li>
                        <li role="presentation"><a href="/logout">Uitloggen</a></li>
                    </ul>
                </nav>
                <h3 class="text-muted">NRG Web</h3>
            </div>
            
            <div class="jumbotron">
                <h1>Welcome Home !!</h1>
                
            </div>
            
            
            <footer class="footer">
                <p>&copy; NRG 2015</p>
            </footer>
            
        </div>
    </body>
    
</html>